### ISSUE TITLE
FileNotFoundError: params-ijepa.yaml when run main.py

### ISSUE THREAD

**Issue by jackwillsmith** [facebookresearch/ijepa#5]
### env
windows11
Python 3.9.13
torch 2.0

### log 
here is log when i run “python main.py   --fname configs/in1k_vith14_ep300.yaml   --devices cuda:0”

```
INFO:root:called-params configs/in1k_vith14_ep300.yaml
INFO:root:loaded params...
{   'data': {   'batch_size': 128,
                'color_jitter_strength': 0.0,
                'crop_scale': [0.3, 1.0],
                'crop_size': 224,
                'image_folder': 'imagenet_full_size/061417/',
                'num_workers': 10,
                'pin_mem': True,
                'root_path': '$replace_this_with_absolute_path_to_your_datasets_directory',
                'use_color_distortion': False,
                'use_gaussian_blur': False,
                'use_horizontal_flip': False},
    'logging': {   'folder': '$replace_this_with_path_for_experiment_logs/vith14.224-bs.2048-ep.300/',
                   'write_tag': 'jepa'},
    'mask': {   'allow_overlap': False,
                'aspect_ratio': [0.75, 1.5],
                'enc_mask_scale': [0.85, 1.0],
                'min_keep': 10,
                'num_enc_masks': 1,
                'num_pred_masks': 4,
                'patch_size': 14,
                'pred_mask_scale': [0.15, 0.2]},
    'meta': {   'copy_data': False,
                'load_checkpoint': False,
                'model_name': 'vit_huge',
                'pred_depth': 12,
                'pred_emb_dim': 384,
                'read_checkpoint': None,
                'use_bfloat16': True},
    'optimization': {   'ema': [0.996, 1.0],
                        'epochs': 300,
                        'final_lr': 1e-06,
                        'final_weight_decay': 0.4,
                        'ipe_scale': 1.0,
                        'lr': 0.001,
                        'start_lr': 0.0002,
                        'warmup': 40,
                        'weight_decay': 0.04}}
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
INFO:root:Running... (rank: 0/1)
Process Process-1:
Traceback (most recent call last):
  File "D:\Program Files\anaconda3\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\Program Files\anaconda3\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "E:\deepLearn\ijepa\main.py", line 55, in process_main
    app_main(args=params)
  File "E:\deepLearn\ijepa\src\train.py", line 129, in main
    with open(dump, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '$replace_this_with_path_for_experiment_logs/vith14.224-bs.2048-ep.300/params-ijepa.yaml'
```

anyone meet is too?

**Comment by MidoAssran** [comment]
Hi @jackwillsmith , you need to specify a logging path in the config and create this directory, see the part ```$replace_this_with_path_for_experiment_logs/vith14.224-bs.2048-ep.300/```

This error is just due to the fact that the specified logging directory does not exist.

**Comment by MidoAssran** [comment]
Note, this is just the path where you want the logs saved, e.g., checkpoints, csv files, etc.
